<?php

namespace App\Traits;

use App\Scopes\AffiliatesScope;
use App\Tenant\Observers\TenantObserver;
use App\Tenant\Scopes\TenantScope;

trait AffiliatesTrait
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub        

        static::addGlobalScope(new AffiliatesScope);
    }
}