<?php

namespace App\Traits;

use App\Scopes\AffiliatesScope;
trait AffiliatesTrait
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub        

        static::addGlobalScope(new AffiliatesScope);
    }
}